### ISSUE TITLE
Better type variable ordering for type applications

### ISSUE THREAD

**Issue by noughtmare** [haskell/random#105]
I think it is more common to explicitly specify the type of thing that you want to generate than it is to specify the generator type, so I would propose to change the type variable ordering to make it easier to use explicit type applications, e.g. change the type signature of `uniform` from

```haskell
uniform :: (RandomGen g, Uniform a) => g -> (a, g)
```

To

```haskell
uniform :: (Uniform a, RandomGen g) => g -> (a, g) 
```

The particular use-case I have right now is using `fromIntegral` to convert the generated numbers to arbitrary length `Integer`s. I currently have to write:

```haskell
f :: StdGen -> (Integer, StdGen)
f g = first fromIntegral (uniform @_ @Word g)
```

But it would be nicer to be able to write:

```haskell
f :: StdGen -> (Integer, StdGen)
f g = first fromIntegral (uniform @Word g)
```

Are there any real-world examples where the current ordering would be preferred?

I also want to acknowledge that this is a breaking change and might be rejected for that reason alone, that would be sad but understandable.

**Comment by Bodigrim** [comment]
I doubt the inconvenience is worth a breaking change :( `@_` is not that bad IMHO. 

However if others feel strongly other way, I would not mind to change this.

**Comment by lehins** [comment]
To be honest with you, I would really like for `a` to come before `g`, it makes total sence:

```haskell
uniform :: forall a g. (Uniform a, RandomGen g) => g -> (a, g) 
```

However. That being a breaking change is somewhat a problem, but even bigger a problem is the consistency with other functions. In particular: `uniformM`, `uniformRM`, `random`, ... These functions are a part of their respective classes and [currently it is not possible to adjust the order of type arguments for class functions](https://stackoverflow.com/questions/54700136/explicit-forall-on-a-type-class-function). Eg. that is not possible without an otherwise redundant synonym: 

```haskell
uniformM :: forall a g m. StatefulGen g m => g -> m a
```
can only be done with:

```haskell
class Uniform a where
  uniformM_ :: StatefulGen g m => g -> m a

uniformM :: forall a g m. StatefulGen g m => g -> m a
uniformM = uniformM_
```

which is quite a bit more of a breaking change than I am willing to accept.

**Comment by lehins** [comment]
After typing up this comment, I realized that what you are suggesting would actually make it more consistent:

```haskell
λ> let g = mkStdGen 56
λ> :set -XTypeApplications
λ> random @Int  g
(4353830680759892024,StdGen {unStdGen = SMGen 8228158190642476075 11319972279577420103})
λ> let g = mkStdGen 56
λ> runStateGen_ g (uniformM @Int)
4353830680759892024
```

I am in favor of fixing this!

**Comment by lehins** [comment]
Reason for this is that the inferred `forall` for `uniformM` is the desired one:

```haskell
λ> :set -fprint-explicit-foralls
λ> :t uniformM
uniformM
  :: forall {a} {g} {m :: * -> *}.
     (Uniform a, StatefulGen g m) =>
     g -> m a
````
adn the one for `uniform` doesn't match:
```haskell
λ> :t uniform
uniform :: forall {g} {a}. (RandomGen g, Uniform a) => g -> (a, g)
```

So I would even consider it a minor bug. Regardless of this, it is a breaking change, so we will target it for `random-1.3.0` just to be safe. @noughtmare would you like to submit a PR?

**Comment by noughtmare** [comment]
I will try to make a quick PR. Which functions should I change? Obviously `uniform` then, but maybe also `uniformR`, `randomM`, and `randomRM`.

I don't think `getStdRandom` and the like need an explicit forall since you could always use type applications on the generating function inside the first argument.

**Comment by lehins** [comment]
Yes, all four:

> Obviously uniform then, but maybe also uniformR, randomM, and randomRM.

I don't think any other functions would benefit as much form a change of type variable order.
