### ISSUE TITLE
Make a minor random-1.2.1 release

### ISSUE THREAD

**Issue by lehins** [haskell/random#110]
Eventually we'll have 1.3.0 release, but considering how much impact on the ecosystem major version upgrade has due to upper bounds, I'd prefer not to rush with breaking changes. For now, I'd like to get various minor improvements that were applied over the year since the last release.

**Comment by Bodigrim** [comment]
Let's wait until GHC 9.2 RC to ensure there are no nasty surprises. Should not be long.

**Comment by lehins** [comment]
Most certainly :+1:22:20, June 6, 2021, Bodigrim ***@***.***>:
Let's wait until GHC 9.2 RC to ensure there are no nasty surprises. Should not be long.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by andreasabel** [comment]
@Bodigrim @lehins
> Let's wait until GHC 9.2 RC to ensure there are no nasty surprises. Should not be long.

I think it is out now.  Would be great to have a GHC 9.2 compatible release of `random` now!

**Comment by lehins** [comment]
@andreasabel I'll try to prepare a release over the weekend.

**Comment by lehins** [comment]
I am preparing a release branch here, if anyone has interest in looking at what's new: https://github.com/haskell/random/compare/v1.2.0...v1.2.1-release-branch

All of the changes are just cherry picks from master of all non-breaking changes.

I also plan to add #95 and hopefully #72 as well into this release

**Comment by lehins** [comment]
Good news. I finally merged all the PRs I wanted to include in 1.2.1 version. Tested it with ghc-9.2-rc as well as all sorts of other architectures. Release is up on hackage: https://hackage.haskell.org/package/random-1.2.1
