### ISSUE TITLE
push 1.1 to hackage and deprecate 1.0.1.3

### ISSUE THREAD

**Issue by cartazio** [haskell/random#17]
actions to do 

(aside: should be do a fancier travis CI formula? )
(not sure if its worth doing a package candidate since doc builders are disabled right now)
-   [x] push 1.1 release (duly tagged on github) to hackage
-   [x] if builder is still busted, used the fuuzetsu http://fuuzetsu.co.uk/blog/posts/2014-01-06-Hackage-documentation-v2.html doc builder script to put docs online
-  [x] deprecate bad release 1.0.1.3
-  [x] move on to more important things

**Comment by ekmett** [comment]
There doesn't seem to be a good way to provide better feedback currently
that I can see.
