### ISSUE TITLE
Please provide instance for (Enum a, Bounded a) for Random

### ISSUE THREAD

**Issue by kvanbere** [haskell/random#21]
It would be really nice to be able to do something like this:

```
> data Action = Code | Eat | Sleep deriving (Bounded, Enum)
> randomR :: IO Action
Eat
```

The implementation for `(Enum a, Bounded a) =>` can cheat a little to get a valid range (psuedo, for randomRIO since it's easier/shorter to show):

```
let lower = fromEnum (minBound :: a)
let upper = fromEnum (maxBound :: a)
return $ toEnum <$> randomRIO (lower, upper)
```

Note the usage of the underlying instance for `Int` to select a constructor.

It would have been magical if we could have just a `Enum a =>` instance, but I can't think of a way to do it.

**Comment by vimuel** [comment]
This would be really nice to have.

**Comment by donkeybonks** [comment]
Ah yes, another +1 on this .. it’s 3 year’s old, I had forgotten all about it .

**Comment by donkeybonks** [comment]
Is PR accepted ?

**Comment by cartazio** [comment]
I’m working on a new release.  Stay tuned.

**Comment by Bodigrim** [comment]
I'm not convinced that sprinkling a couple of `fromEnum` / `toEnum` is that much of boilerplate. It certainly does not justify introducing overlapping instances. 

However, I would not particularly oppose a PR, introducing `uniformBoundedEnum :: (Enum a, Bounded a, StatefulGen g m) => g -> m a` or something similar.

**Comment by Shimuuar** [comment]
I think we should introduce newtype wrapper which allows to derive Uniform/UniformRange instances using DerivingVia

```haskell
newtype UniformEnum a = UniformEnum a

instance Enum a => UniformRange (UnniformEnum a) where
  ...
instance (Bounded a, Enum a) => Uniform (UnniformEnum a) where
  ...

data RGB = R | G | B
  deriving (Enum.Bounded)
  deriving Uniform via UniformEnum RGB
```

**Comment by chessai** [comment]
@Shimuuar that looks good to me!

**Comment by Bodigrim** [comment]
Closing as done in #104. Feel free to reopen if there is a specific motivation to use this feature via old `Random` interface.

**Comment by georgefst** [comment]
> ```hs
> newtype UniformEnum a = UniformEnum a
> 
> instance Enum a => UniformRange (UniformEnum a) where
>   ...
> instance (Bounded a, Enum a) => Uniform (UniformEnum a) where
>   ...
> 
> data RGB = R | G | B
>   deriving (Enum, Bounded)
>   deriving Uniform via UniformEnum RGB
> ```
> [typos corrected]

Sorry to resurrect an old thread, but I felt I should point out that this just doesn't work:
```
• Couldn't match representation of type: m (UniformEnum RGB)
                           with that of: m RGB
    arising from the coercion of the method ‘uniformM’
      from type ‘forall g (m :: * -> *).
                 System.Random.Internal.StatefulGen g m =>
                 g -> m (UniformEnum RGB)’
        to type ‘forall g (m :: * -> *).
                 System.Random.Internal.StatefulGen g m =>
                 g -> m RGB’
  Note: We cannot know what roles the parameters to ‘m’ have;
        we must assume that the role is nominal.
• When deriving the instance for (Uniform RGB)typecheck(GHC-18872)
```
I'm not all that familiar with roles, so I don't know if there's a simple way around this. I suspect _not_, since this looks similar at a glance to what @amesgen wrestled with in #96.

**Comment by lehins** [comment]
@georgefst Here is the reason why it doesn't work: https://github.com/haskell/random/issues/185#issuecomment-2823069073
