### ISSUE TITLE
The seeds generated by split are not independent

### ISSUE THREAD

**Issue by idontgetoutmuch** [haskell/random#25]
See - https://ghc.haskell.org/trac/ghc/ticket/3620 (and also https://ghc.haskell.org/trac/ghc/ticket/3575) I just ran the example https://ghc.haskell.org/trac/ghc/attachment/ticket/3620/RandomnessTest2.hs and got

```
Generated 2000 pairs of numbers from 0 to 1 -- 1299 pairs contained equal numbers and we expected about 1000.
Generated 3000 pairs of numbers from 0 to 2 -- 187 pairs contained equal numbers and we expected about 1000.
Generated 4000 pairs of numbers from 0 to 3 -- 101 pairs contained equal numbers and we expected about 1000.
Generated 5000 pairs of numbers from 0 to 4 -- 271 pairs contained equal numbers and we expected about 1000.
Generated 6000 pairs of numbers from 0 to 5 -- 359 pairs contained equal numbers and we expected about 1000.
Generated 7000 pairs of numbers from 0 to 6 -- 1401 pairs contained equal numbers and we expected about 1000.
Generated 8000 pairs of numbers from 0 to 7 -- 158 pairs contained equal numbers and we expected about 1000.
Generated 9000 pairs of numbers from 0 to 8 -- 53 pairs contained equal numbers and we expected about 1000.
Generated 10000 pairs of numbers from 0 to 9 -- 535 pairs contained equal numbers and we expected about 1000.
Generated 11000 pairs of numbers from 0 to 10 -- 0 pairs contained equal numbers and we expected about 1000.
Generated 12000 pairs of numbers from 0 to 11 -- 70 pairs contained equal numbers and we expected about 1000.
Generated 13000 pairs of numbers from 0 to 12 -- 0 pairs contained equal numbers and we expected about 1000.
Generated 14000 pairs of numbers from 0 to 13 -- 0 pairs contained equal numbers and we expected about 1000.
Generated 15000 pairs of numbers from 0 to 14 -- 783 pairs contained equal numbers and we expected about 1000.
```

On the other hand the example from http://publications.lib.chalmers.se/records/fulltext/183348/local_183348.pdf now seems to work

```
> quickCheckWith stdArgs { maxSuccess = 10000 } prop_shouldFail
*** Failed! Falsifiable (after 2 tests): 
((),Int14 13)
Int14 13
```

**Comment by idontgetoutmuch** [comment]
I just tried the same test but using https://hackage.haskell.org/package/tf-random

```
module Main where

import Control.Monad
import System.Random.TF.Gen
import System.Random.TF.Instances

splitN :: (RandomGen g) => Int -> g -> ([g], g)
splitN 0 g = ([], g)
splitN n g = (g1:l, g')
  where
  (l, g') = splitN (n-1) g2
  (g1, g2) = split g

-- The funny splitting operation.
split' :: (RandomGen g) => g -> (g, g)
split' g = (g12, g21)
  where
  (g1, g2) = split g
  (_, g12) = split g1
  (g21, _) = split g2

-- This test checks if generators created by calling split 2 times are independent.
-- It generates pairs of integers from 0 to n-1, using split' to
-- generate both numbers using one seed. Then it counts how often the
-- two numbers are equal.
test :: (RandomGen g) => Int -> Int -> g -> Int
test numTests n g = equals
  where
  (gs, _) = splitN numTests g
  equals = count id $ map single gs
  count p l = length $ filter p l
  single g' = (fst $ randomR (0, n-1) g1) == (fst $ randomR (0, n-1) g2)
    where
    (g1, g2) = split' g'

main = do
  let g = seedTFGen (42, 42, 42, 42)
  forM_ [2..15] $ \i -> do
    let actual = test (i * 1000) i g
    putStrLn $ "Generated " ++ show (i * 1000)
      ++ " pairs of numbers from 0 to " ++ show (i - 1)
      ++ " -- " ++ show actual ++ " pairs contained equal numbers "
      ++ "and we expected about 1000."
```

and this gives what seems to be a correct result

```
Generated 2000 pairs of numbers from 0 to 1 -- 1013 pairs contained equal numbers and we expected about 1000.
Generated 3000 pairs of numbers from 0 to 2 -- 977 pairs contained equal numbers and we expected about 1000.
Generated 4000 pairs of numbers from 0 to 3 -- 1016 pairs contained equal numbers and we expected about 1000.
Generated 5000 pairs of numbers from 0 to 4 -- 996 pairs contained equal numbers and we expected about 1000.
Generated 6000 pairs of numbers from 0 to 5 -- 988 pairs contained equal numbers and we expected about 1000.
Generated 7000 pairs of numbers from 0 to 6 -- 967 pairs contained equal numbers and we expected about 1000.
Generated 8000 pairs of numbers from 0 to 7 -- 976 pairs contained equal numbers and we expected about 1000.
Generated 9000 pairs of numbers from 0 to 8 -- 975 pairs contained equal numbers and we expected about 1000.
Generated 10000 pairs of numbers from 0 to 9 -- 992 pairs contained equal numbers and we expected about 1000.
Generated 11000 pairs of numbers from 0 to 10 -- 986 pairs contained equal numbers and we expected about 1000.
Generated 12000 pairs of numbers from 0 to 11 -- 991 pairs contained equal numbers and we expected about 1000.
Generated 13000 pairs of numbers from 0 to 12 -- 973 pairs contained equal numbers and we expected about 1000.
Generated 14000 pairs of numbers from 0 to 13 -- 990 pairs contained equal numbers and we expected about 1000.
Generated 15000 pairs of numbers from 0 to 14 -- 996 pairs contained equal numbers and we expected about 1000.
```

**Comment by cartazio** [comment]
Sounds like weve got some work to do

**Comment by cartazio** [comment]
I kinda suspected the current splitting design had this sort of problem but
it's good we now have evidence!

**Comment by gbaz** [comment]
This splitting design has been known to have this problem for the past six years going by those tickets -- I think longer. And the guarantees made by the random library have _never suggested otherwise_. So I think a better random _should have better splitting_ but I also think that this is not an immediate "must fix" bug, but a property that should inform our selection of a new random algorithm in the coming future.

**Comment by cartazio** [comment]
agreed, and i think its worth burning some time on

1) building some infrastructure to compare different algorithms in both
quality of randomness AND in performance

2) exploring preexisting algorithms, and experimenting with new approaches
informed by preexisting work AND buttressed by having a really good quality
RNG testing infrastructure that we can be systematic about

**Comment by idontgetoutmuch** [comment]
@gbaz by "guarantees made by the random library have never suggested otherwise" do you mean the haddock comment

> but very little work has been done on statistically robust implementations of split ([System.Random,System.Random] are the only examples we know of)

or the comment in the actual implementation

```
-- no statistical foundation for this!
```

or is there something I am missing?

**Comment by gbaz** [comment]
> The result of repeatedly using next should be at least as statistically robust as the Minimal Standard Random Number Generator described by [System.Random, System.Random]. Until more is known about implementations of split, all we require is that split deliver generators that are (a) not identical and (b) independently robust in the sense just given.

This makes clear to me that there was never a promise of statistical independence between split generators -- just that independently each generator is robust.

So this is well documented behaviour. (Which doesn' t mean it is good behaviour, and doesn't mean we shouldn't replace it with better behaviour now that we have new research and implementations).

**Comment by cartazio** [comment]
agreed. And some effort and time this summer should be spent exploring the
choices

**Comment by idontgetoutmuch** [comment]
The second example I gave, rolling a die and getting 53668 sixes and no other numbers, does *not* use `split` just `randomR`.

**Comment by idontgetoutmuch** [comment]
Some old related discussion: https://mail.haskell.org/pipermail/haskell-cafe/2010-November/thread.html#85959

**Comment by gbaz** [comment]
The second example doesn't just use `randomR` -- it calls `mkStdGen` for each roll individually, which creates a new generator. As far as I know, `mkStdGen` in turn calls split.

Regardless, it is never considered the case that making new generators without introducing explicit randomness should somehow guarantee that the sequence of generators you make are mutually uncorrelated.

If you change the example to share the same generator, the problem does not exist. We could perhaps improve the documentation to more clearly warn against this bad usage pattern.

**Comment by dolio** [comment]
> The second example doesn't just use `randomR` -- it calls `mkStdGen` for each roll individually, which creates a new generator. As far as I know, `mkStdGen` in turn calls split.

I don't think it even does that. It just creates a new generator from a specific seed. The complaint is that seeding with N doesn't differ from seeding with (N+1) when generating a single number from 1 to 6.

**Comment by idontgetoutmuch** [comment]
I believe some comparison work has been done. I am recording these links below for information.

https://github.com/nkartashov/SplitMix
https://github.com/nkartashov/prng-test
https://github.com/nkartashov/prng-bench
https://github.com/nkartashov/htestu

**Comment by cartazio** [comment]
Yup. We should both work through running validation benchmarks from those
repos / audit the statistical and performance benchmarks that the student
worked on.

**Comment by Blaisorblade** [comment]
After seeing `split` docs, I wanted to mention a library designed for parallel Monte Carlo: http://www.sprng.org/. [This page](http://www.sprng.org/Version5.0/generators.html) describes the algorithms used and the docs also describe the performed testing; the library was also published on ACM ToMS with 275 citations. It also *doesn't* use cryptographic-strength PRNGs, unlike the ones mentioned in the 2010 haskell-cafe thread (https://mail.haskell.org/pipermail/haskell-cafe/2010-November/thread.html#85959),
and the docs mention TestU01 (the standard benchmark mentioned also in https://github.com/nkartashov/htestu).

I haven't validated the library myself, but it was recommended by my professor in Monte Carlo methods and random number generation, and he wanted to use it for his own publications. Since physicists know their stats, it looks promising.

The actual algs aren't so much math (though the validation work isn't going to be trivial). Anyone want to take a stab at this?

**Comment by cartazio** [comment]
thanks for sharing this, I"ll take a look soon! (i've some summer projects
with september deadlines hot on my tail, but i'm keen to give random some
much needed love this fall)

**Comment by tom-bop** [comment]
Any news on this front?

**Comment by cartazio** [comment]
yup, https://github.com/cartazio/random/tree/v1.2.0 (plus some commits i've locally that i really should push) is progressing to a release

@tom-bop  whats your needs/ context?

**Comment by cartazio** [comment]
(i do need to figure out what the major versioning / migrration path will be, 1.2 is gonna try to be mostly drop in compatible, with minimal fix ups, some later versions will have more machinery / better apis
)

**Comment by idontgetoutmuch** [comment]
@tom-bop my recommendation is not to use this library. If you really want independent generators then use either https://hackage.haskell.org/package/tf-random or https://hackage.haskell.org/package/splitmix.

**Comment by cartazio** [comment]
@idontgetoutmuch : http://www.pcg-random.org/posts/bugs-in-splitmix.html :)

**Comment by idontgetoutmuch** [comment]
@cartazio excellent - that will teach me to trust people who told me it was the greatest thing since sliced bread - I will have to read the article in more depth

**Comment by cartazio** [comment]
Yeah ... there’s some differences between the jdk version and reference
etc.

Tf random also had some issues when I ran those test harnesses.  Though I
think you rightfully pointed out there’s some issues on interpretation.

So I’m trying to make sure we have a range of tools.  And easy ways to
build sampling strategies of various flavors based on desired quality and
perf targets.

**Comment by idontgetoutmuch** [comment]
https://alexey.kuleshevi.ch/blog/2019/12/21/random-benchmarks/

**Comment by cartazio** [comment]
Yup!
Agreed.

Been getting vector into a good place the past few weeks (hope you like the
new release!). This whole backlog is next.

**Comment by peteroupc** [comment]
For your information:

I have written notes on how to test PRNGs and hash functions for appropriate randomness in "[Testing PRNGs for High-Quality Randomness](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomtest.md)".  As relevant here, there are many kinds of hash functions that could serve as the basis for a good-quality splittable RNG construction (not just Threefry), and there are at least four kinds of sequences that are suitable for testing splittable RNGs.
