### ISSUE TITLE
randomR too slow

### ISSUE THREAD

**Issue by thomie** [haskell/random#29]
See https://ghc.haskell.org/trac/ghc/ticket/2280

**Comment by cartazio** [comment]
There's a lot of issues with random, and one of this summer's gsoc students
is helping out with doing some huge improvements. Stay tuned!

**Comment by idontgetoutmuch** [comment]
I believe the student recorded his work here

https://github.com/nkartashov/SplitMix
https://github.com/nkartashov/prng-test
https://github.com/nkartashov/prng-bench
https://github.com/nkartashov/htestu

**Comment by cartazio** [comment]
this work will be done in #31
