### ISSUE TITLE
mkStdGen and the Read instance lose a lot of entropy

### ISSUE THREAD

**Issue by kuk0** [haskell/random#35]
I'm referring to this code:
```
stdFromString         :: String -> (StdGen, String)
stdFromString s        = (mkStdGen num, rest)
        where (cs, rest) = splitAt 6 s
              num        = foldl (\a x -> x + 3 * a) 1 (map ord cs)
```
which reads 6 bytes, but only produces a number (IINM) between 729 and 93549, which is ~16 bits! while the state of the `StdGen` is almost 62(?) bits - two `Int32`s...

similarly,
```
mkStdGen32 :: Int32 -> StdGen
```
takes only 31 bits of input, so `q` in `(q, s1) = s `divMod` 2147483562` will be <= 1...
that looks suboptimal...

consequently, also `mkStdRNG` based on time will use at most 31 bits

**Comment by cartazio** [comment]
See the v2 ticket.  These and a lot of other issues will be addressed with thst work.  I'm spending part of my weekend whipping that into shape for feedback. Please subscribe to that ticket so we can analyze the hell out of the v2 branch once I push it :)
