### ISSUE TITLE
Add NOINLINE pragma for theStdGen

### ISSUE THREAD

**Issue by chowells79** [haskell/random#46]
Top-level values initialized in IO with `unsafePerformIO` can be inlined, causing much awfulness.  There was a case in IRC earlier that appeared to be caused by inlining `theStdGen`.  Regardless of whether that was actually the cause, it should definitely be marked NOINLINE.

Proposal: add the pragma as such:

```
{-# NOINLINE theStdGen #-}
theStdGen :: IORef StdGen
theStdGen  = unsafePerformIO $ do
    rng <- mkStdRNG 0
    newIORef rng
```

**Comment by treeowl** [comment]
I spend fifteen to twenty minutes trying to figure out whether this can actually cause a problem before coming over to file a ticket and finding yours. I still don't know for sure if it can pop up, but we should definitely do this regardless. We certainly never want `theStdGen` to inline ever, so marking it `NOINLINE` certainly should be okay.

**Comment by cartazio** [comment]
I’ve a release that removes this along with a lot of major version changes
pending.  Will post to hackage early next week after doing some trustee
level surgery. Amidst some family travel at the moment

**Comment by idontgetoutmuch** [comment]
@treeowl I am curious as to why you use this package given it has many problems. The QuickCheck folks abandoned it a long time ago because of problems they had with it and replaced it with https://hackage.haskell.org/package/tf-random. Of course there are many other choices depending on what you want from your RNG.

**Comment by cartazio** [comment]
master wont have these issues, no gonna fix the old ones,
