### ISSUE TITLE
randomR could produce NaNs when the upper bound is infinity

### ISSUE THREAD

**Issue by shaobo-he** [haskell/random#54]
When the upper bound is infinity, NaNs could be produced. For example,

```haskell
filter (\x-> x/= (1/0)) $ randomRs ((0::Float), 1/0) $ mkStdGen 0
[NaN,NaN,NaN
```

Although it's unclear what should be produced when the upper bound is infinity, I don't think NaNs should be there anyways.

**Comment by cartazio** [comment]
Agreed.  This is def a bug. I’ll make sure the next release  and the
associated old-random package don’t have this issue

**Comment by Bodigrim** [comment]
`NaN` is caused by `0 * ±Infinity`, happening in `uniformRM` when `uniformFloat01M` returns exactly 0 or 1. 

We can probably guard this case explicitly:

```haskell
instance UniformRange Float where
  uniformRM (l, h) g
    | isNaN l = l 
    | isNaN h = h 
    | l == h = return l
    | isInfinite l, isInfinite h = 0/0
    | isInfinite l = l 
    | isInfinite h = h 
    | otherwise = do
      x <- uniformFloat01M g
      return $ x * l + (1 - x) * h
```

@curiousleo what do you think about it?

**Comment by lehins** [comment]
@Bodigrim you might be interested to look at discussion in this PR: https://github.com/idontgetoutmuch/random/pull/138

**Comment by curiousleo** [comment]
Or directly here: https://hackage.haskell.org/package/random-1.2.0/docs/System-Random-Stateful.html#g:14

@Bodigrim great minds think alike :) [Here's what I cooked up](https://github.com/curiousleo/random-float/blob/dbaaaa5cbe1fa4730721bd536a9edbdadcebd46b/src/Uniform.hs#L43-L50) for my "truly random floats" experiment.

Here's my critique.

```haskell
    | isNaN l = l 
    | isNaN h = h 
```
The `isNaN` guards unnecessary; if one of `l` or `h` is `NaN`, the result will be `NaN`.

```haskell
    | l == h = return l
```
(This guard already exists, added here: https://github.com/idontgetoutmuch/random/pull/169)

```haskell
    | isInfinite l, isInfinite h = 0/0
```
This looks like a strong bias towards positive infinity to me. Why should generating a number in `[-Inf, +Inf]` always result in `+Inf`? IMO the result here should either be `NaN` (that's what you get right now), or it should be `+Inf` or `-Inf` each with p=0.5.

```haskell
    | isInfinite l = l 
    | isInfinite h = h 
```
This is already the current behaviour for `x \in (0,1)`. If `x == 0` or `x == 1`, you can currently get `NaN` instead, as you pointed out. This case is currently not documented.

I see two alternatives:
- We document that when `l` or `h` is infinite, you can get a `NaN` back (if `x == 1` or `x == 0`)
- We add guards for infinities. My proposal here would be something like the following.

```haskell
instance UniformRange Float where
  uniformRM (l, h) g
    | l == h = return l
    | isInfinite l && isInfinite h = bool negate id <$> uniformM
    | isInfinite l = l 
    | isInfinite h = h 
    | otherwise = do
      x <- uniformFloat01M g
      return $ x * l + (1 - x) * h
```

**Comment by idontgetoutmuch** [comment]
In the email notification I just received, I see

```
    | isInfinite l && isInfinite h = bool negate id <$> uniformM
```

I think asking to sample a range with infinties is indication that the user has made a mistake. If they really wanted +Inf / -Inf with equal probability then it would be much better for them to be explicit about it. I'd much prefer a NaN here.
