### ISSUE TITLE
System/Random.hs:43:1: warning: [-Wtabs]

### ISSUE THREAD

**Issue by p-alik** [haskell/random#55]
`stack build` with [lts-13.26](https://www.stackage.org/lts-13.26) warns

```
random              >
random              > /tmp/stack5350/random-1.1/System/Random.hs:43:1: warning: [-Wtabs]
random              >     Tab character found here, and in 74 further locations.
random              >     Please use spaces instead.
random              >    |
random              > 43 |         (
random              >    | ^^^^^^^^
```

@nagaflokhu mentioned it also in [#50](https://github.com/haskell/random/issues/50#issue-383642492)
> There are also warnings about tab characters further up cabal's message.

https://github.com/haskell/random/blob/cfdfe6f09ad414fde5b855cc5f90207533413241/System/Random.hs#L42-L43

**Comment by lehins** [comment]
All compile time warnings have been taken care of. See #62
