### ISSUE TITLE
Unable to build/install on Fedora 31

### ISSUE THREAD

**Issue by 3n-k1** [haskell/random#56]
When attempting to install this library, either with `stack install random` or `stack build` (in a project with random as a dependency), I get the following output:

```
Using latest snapshot resolver: lts-14.16
[1 of 2] Compiling Main             ( /home/tay/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/tay/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /home/tay/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/tay/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /home/tay/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 ...
random> configure
random> Warning: random.cabal:15:2: Tabs used as indentation at 15:2, 16:2, 17:2
random> Configuring random-1.1...
random> build
random> Preprocessing library for random-1.1..
random> Building library for random-1.1..
random> [1 of 1] Compiling System.Random
random> 
random> /tmp/stack2769782/random-1.1/System/Random.hs:43:1: warning: [-Wtabs]
random>     Tab character found here, and in 74 further locations.
random>     Please use spaces instead.
random>    |
random> 43 |         (
random>    | ^^^^^^^^
random> 
random> copy/register
random> Installing library in /home/tay/.stack/snapshots/x86_64-linux-tinfo6/7b7c19e9c03a08bbf05b457de9f8a9b8c88f0149557f025ff0738c135bdb665a/8.6.5/lib/x86_64-linux-ghc-8.6.5/random-1.1-3ypV4EIycgb35PKjTYYr5q
random> /usr/bin/strip:/home/tay/.stack/snapshots/x86_64-linux-tinfo6/7b7c19e9c03a08bbf05b457de9f8a9b8c88f0149557f025ff0738c135bdb665a/8.6.5/lib/x86_64-linux-ghc-8.6.5/libHSrandom-1.1-3ypV4EIycgb35PKjTYYr5q-ghc8.6.5.so[.gnu.build.attributes]: corrupt GNU build attribute note: wrong note type: bad value
'cabal copy' failed.  Error message:

--  While building package random-1.1 using:
      /home/tay/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 copy
    Process exited with code: ExitFailure 1

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file that doesn't exist). Running 'cabal check' may point out these issues.
```
System info:
```
λ uname -a
Linux localhost.localdomain 5.3.11-300.fc31.x86_64 #1 SMP Tue Nov 12 19:08:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
I can install the package just fine with DNF, but I'm unable to use the package with stack.

**Comment by cartazio** [comment]
Strange. Sounds like a bug with stack.
 I use cabal install and every Haskell package supports cabal.

The crux of the issue might be that stack is about building apps rather
than libraries and thus some part of stack hard codes the assumption that a
given build target has a main module.

So def an issue with using stack rather than cabal for building libraries

**Comment by cartazio** [comment]
I’m going to close this issue for now since the fix seems to be using stack with a library as a build target rather than as a dependency for an app. For globally installing libraries for experimentation cabal install should work fine.

**Comment by cartazio** [comment]
That said, if additional information surfaces to the contrary please share. 

And either way thanks for the time taken to report your issue in enough detail

**Comment by 3n-k1** [comment]
Thanks for getting back to me so quickly. My apologies for posting it here. I'm *very* new to Haskell's tooling.

It definitely seems to be a regression *somewhere*, since my Fedora 30 machine can stack install random just fine. I'll try reporting this to stack, and I'll post back here if anything new comes up.

**Comment by cartazio** [comment]
Not a problem!

I do recommend trying out cabal, via the cabal-install package.
Cabal-install v3 is quite nice and should work.  And if not you have my
full attention and support in sleuthing out the underlying problem.  It’s
friendly users and contributors that help motivate any decent maintainer.
