### ISSUE TITLE
read :: StdGen fails for strings longer than 6

### ISSUE THREAD

**Issue by joeyh** [haskell/random#59]
ghci> read "abcdef" :: StdGen
    36217 1
    ghci> read "abcdefg" :: StdGen
    ** * Exception: Prelude.read: no parse

This is contrary to the documentation: "It guarantees to succeed on any string. "

random-1.1  
ghc-8.6.5

**Comment by cartazio** [comment]
The documentation in read or in random. ?

I do strongly recommend using the pcg package for Rng engineering today.

The next major release of random will have pcg as one of the default
options.

I’m not sure what you’re trying to do with reading here?  It doesn’t look
like a deserialize to me ?

**Comment by cartazio** [comment]
What’s the intent or goal you want to achieve here ? That can help inform
some of the planned new library work

**Comment by andrewthad** [comment]
It's a [guarantee provided in the docs for random](https://github.com/haskell/random/blob/22a2a16bd62edd553b4f7f2e9eedc26cbf8850d8/src/System/Random.hs#L183):

> In addition, 'reads' may be used to map an arbitrary string (not necessarily one produced by 'show') onto a value of type 'StdGen'. In general, the 'Read' instance of 'StdGen' has the following properties:
>
> * It guarantees to succeed on any string.
> * It guarantees to consume only a finite portion of the string.
> * Different argument strings are likely to result in different results.

This is a weird thing to do with `reads`. Removing the broken `Read` instance for `StdGen` is a reasonable solution and deleting the associated documentation would be a reasonable fix.

**Comment by cartazio** [comment]
Derp.  Yeah. Agreed on all fronts.  Been in a cavern on new random and
forgot about this cute little rough edge.

**Comment by idontgetoutmuch** [comment]
I'd recommend using [splitmix](https://hackage.haskell.org/package/splitmix) as

  * It's the fastest
 *  Passes e.g. bigCrush so plenty good enough for non-cryptographic applications
 * Has a good `split` function
 * Is used by [QuickCheck](https://hackage.haskell.org/package/QuickCheck)

See here for the details on speed and quality  (which you can run yourself ):

* https://alexey.kuleshevi.ch/blog/2019/12/21/random-benchmarks/
* https://github.com/tweag/random-quality/tree/master/results

**Comment by cartazio** [comment]
Pcg does better on big crush last I checked than splitmix. But either is
good.

**Comment by curiousleo** [comment]
> Pcg does better on big crush last I checked than splitmix.

SplitMix passes all BigCrush tests: https://github.com/tweag/random-quality/blob/master/results/splitmix-word32-testu01-bigcrush#L3775-L3782

**Comment by lehins** [comment]
Fixed. `Read` instance was removed in `random-1.2`. See #62
