### ISSUE TITLE
Hackage cannot render tables in README

### ISSUE THREAD

**Issue by Bodigrim** [haskell/random#66]
Hackage does not support GitHub Flavored Markdown for tables, so `README` on the package page looks badly: https://hackage.haskell.org/package/random-1.2.0#readme 

This issue has been filed as https://github.com/haskell/hackage-server/issues/877 (and received no reaction in a month).

I think that in our particular case we could possibly sacrifice tables and just list badges one by one without captions (they are pretty self-descriptive).

**Comment by lehins** [comment]
I don't think we should work around bugs in Hackage. I knew about this bug for some time now and if more people will use tables in their readmes and changelogs, maybe that issue will get more attention.

In other words I am totally against sacrificing tables. It looks great on stackage, check it out: https://www.stackage.org/package/Color

**Comment by Bodigrim** [comment]
I know, I already checked Stackage for my packages with tables in `README` :)

**Comment by lehins** [comment]
Yeah, there are quite a few packages that rely on tables. I am closing this issue as it is really a problem on Hackage, which hopefully will get fixed some day and then we'll get nice looking readme and [changelog](https://hackage.haskell.org/package/random-1.2.0/changelog)(see "Issues addressed" section) on Hackage
