### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by lehins** [haskell/random#84]
Travis is done with open source. Stalled builds are a major obstacle (see #83), time to switch to something else, github actions seems like a very reasonable alternative.

**Comment by Bodigrim** [comment]
I've been migrating other projects (https://github.com/haskell/bytestring/pull/331/files, https://github.com/haskell/unix/pull/165); so far GitHub Actions look good. 

Do we wish to continue with builds against every minor GHC release? My suggestion is to test only major releases on Ubuntu + the latest release on MacOS/Windows + stack/coverage build.

**Comment by curiousleo** [comment]
> time to switch to something else, github actions seems like a very reasonable alternative.

:+1: 

> My suggestion is to test only major releases on Ubuntu + the latest release on MacOS/Windows + stack/coverage build.

That sounds reasonable to me.
