### ISSUE TITLE
Untie random-1.1 from time

### ISSUE THREAD

**Issue by Bodigrim** [haskell/random#88]
I am working on refactoring `bytestring` test suite. It is currently organized as two packages. There is a `bytestring` package, which reside in a top-level folder, and a `bytestring-tests` package in `tests` sub-folder with the following configuration:

```cabal
test-suite {foo,bar,baz}
  hs-source-dirs:   . ..
  main-is:          {Foo,Bar,Baz}.hs
  other-modules:    Data.ByteString
                    Data.ByteString.Char8
                    Data.ByteString.Internal
                    Data.ByteString.Lazy
                    Data.ByteString.Lazy.Char8
                    Data.ByteString.Lazy.Internal
                    Data.ByteString.Short
                    Data.ByteString.Short.Internal
                    ...many more...
  build-depends:    base, ghc-prim, deepseq, random,
                    tasty, tasty-quickcheck, QuickCheck
```

So tests do not depend on `bytestring` package explicitly, but rather just happen to share source files. This is unfortunate for many reasons. For example, each test component recompiles all modules of `bytestring` anew. Tooling such as HLS cannot figure out which source file belongs to what. But most importantly this way we do not actually test `bytestring` package, because there are no guarantees that the configuration in `bytestring.cabal` (GHC flags, C sources, etc.) is the same.

An obvious solution is to abandon the hack with `hs-source-dirs: ..` and add `bytestring` as a proper `build-depends` of `bytestring-tests` package. This still does not work in a satisfactory manner, because now any change to `bytestring` causes rebuilding of `unix`, `random`, `directory`, `QuickCheck`, `process`, `optparse-applicative`, `tasty`, `tasty-quickcheck` (all of them depend on `bytestring` transitively) and, as you can imagine, it takes obnoxiously long for any sort of interactive development.

Ideally I would like to eliminate `bytestring` as a transitive dependency of the test suite. Not only it would enable us to run tests reasonably quick, but also the very reason for having a separate package `bytestring-tests` would disappear.

I patched `optparse-applicative` and `tasty` ecosystem so that they no longer depend on `bytestring`, when compiled with right flags. While `random-1.2` immediately depends on `bytestring`, tests (and `QuickCheck`) are happy to stick to `random-1.1`.

This endeavour was quite successful for Linux and MacOS builds, but there is a nasty complication on Windows. `random-1.1` depends on `time` as a source of entropy for the global random number generator. And on Windows platform `time` happen to depend on `Win32`, which depends on `bytestring`, which makes it a circular dependency.

While strategically I would like to deal somehow with `bytestring` dependency of `random-1.2+`, its next release does not look happening soon enough. I would like to untie `random-1.1` from `time` and release it as `random-1.1.0.1`. There are two possible courses of actions:

* One can make `time` an optional dependency of `random-1.1`, guarded by a Cabal flag. Users compiling with `time` disabled would lose some (but not all) bits of entropy in `theStdGen`. A patch takes only couple of lines: https://github.com/Bodigrim/random/commit/eb9f9c51c69bde50646e9943a591548f724ff2ea

* Or we can switch the source of entropy from `time` to `splitmix-0.1.0.3` (note that the latter does not normally depend on `time`). This way we there is no need for a new flag, and entropy becomes better than in `random-1.1`. Patch is also very small: https://github.com/Bodigrim/random/commit/1686804d8f40d77c8bcdf5ebefda2edf618a8e41

I'm mildly in favor of the second approach, because it improves and does not complicate things.

**Comment by lehins** [comment]
@Bodigrim I prefer the first approach of adding a simple flag that allows disabling `time`, because it is less invasive and solves your problem with `bytestring` test suite, which is really the only reason for making this release `random-1.1.0.1`.

With regards to the approach of using `MIN_VERSION_*`  instead of defining a special CPP macro, I believe it will not work, because as far as I know the macro is only available since ghc-7.10, so despite that the approach itself is kinda cute `#ifdef MIN_VERSION_time` and such will need to be replaced with an actual cpp definition, something like:
```
    if flag(time)
      cpp-options: -DTIME
```

Also instead of hardcoding `let (sec, psec) = (0, 0)`, why not to reuse the `getTime` ffi call that is already defined for NHC?

**Comment by Bodigrim** [comment]
> With regards to the approach of using `MIN_VERSION_*` instead of defining a special CPP macro, I believe it will not work, because as far as I know the macro is only available since ghc-7.10

There are couple of `MIN_VERSION_base` below, which seem to work fine. And I succeeded to build it with GHC 7.0.

https://github.com/haskell/random/blob/cfdfe6f09ad414fde5b855cc5f90207533413241/System/Random.hs#L97-L99
https://github.com/haskell/random/blob/cfdfe6f09ad414fde5b855cc5f90207533413241/System/Random.hs#L113-L120

However, I don't mind to throw `-DTIME`, just to be on the safe side.

**Comment by lehins** [comment]
My apologies, it is not ghc-7.10, but ghc-8.0.1 to be precise, that added `MIN_VERSION_pkgname`  macro: https://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/phases.html#standard-cpp-macros

I suspect however that cabal might be taking care of backwards compatibility nowadays, because I vividly remember this macro not working on older ghc. Just to be on a safe side in order not to brake all those all ancient setups lets use a `-DTIME`

**Comment by lehins** [comment]
@Bodigrim I honestly can't remember the setup I had in which the macro didn't work as expected. Reading up on it now and trying a few things it seems like it should really work just fine with older ghc. However, I really do remember having a problem with it at some point, maybe I just did something wrong back then, it's always possible ;)

**Comment by Bodigrim** [comment]
Ah, it does not solve my conundrum with `bytestring`, because there appear to be other packages depending on `Win32`. Closing, sorry to trouble.
